$base = "C:\R\LeafOS0.2.1\ProjectLeaf\leafos_taskpack\config\experts\yellow"
function WriteExpert($name, $content) {
	Set-Content -Path (Join-Path $base "$name.json") -Value $content
}

$repo = "DavidAU/Qwen3.6-27B-Fable-Fusion-711-Uncensored-Heretic-NM-DAU-NEO-MAX-MTP-GGUF"

# Router
WriteExpert "yellow-router-fast" '{"schema":"leafos.expert.v1","id":"yellow-router-fast","model_ref":"qwen3.6-27b-fable","source_repo":"'+$repo+'","revision":"main","parameters_b":27,"provider":"llama.cpp","placement":"local","stack_segment":"local_gpu","endpoint_ref":"local-router","quantization":"IQ2_M_MTP","estimated_memory_gib":6.5,"context_tokens":32768,"capabilities":["route.fast"],"fallback_chain":["yellow-router-primary","yellow-router-conservative"],"enabled":false}'
WriteExpert "yellow-router-primary" '{"schema":"leafos.expert.v1","id":"yellow-router-primary","model_ref":"qwen3.6-27b-fable","source_repo":"'+$repo+'","revision":"main","parameters_b":27,"provider":"llama.cpp","placement":"local","stack_segment":"local_gpu","endpoint_ref":"local-router","quantization":"IQ3_M_MTP","estimated_memory_gib":8.0,"context_tokens":32768,"capabilities":["route.primary"],"fallback_chain":["yellow-router-conservative"],"enabled":false}'
WriteExpert "yellow-router-conservative" '{"schema":"leafos.expert.v1","id":"yellow-router-conservative","model_ref":"qwen3.6-27b-fable","source_repo":"'+$repo+'","revision":"main","parameters_b":27,"provider":"llama.cpp","placement":"local","stack_segment":"local_cpu","endpoint_ref":"local-router","quantization":"IQ4_XS","estimated_memory_gib":10.0,"context_tokens":32768,"capabilities":["route.conservative"],"fallback_chain":["yellow-router-fast"],"enabled":false}'

# Brain
WriteExpert "yellow-brain-feeder" '{"schema":"leafos.expert.v1","id":"yellow-brain-feeder","model_ref":"qwen3.6-27b-fable","source_repo":"'+$repo+'","revision":"main","parameters_b":27,"provider":"llama.cpp","placement":"local","stack_segment":"local_cpu","endpoint_ref":"local-brain","quantization":"IQ4_XS","estimated_memory_gib":10.0,"context_tokens":32768,"capabilities":["proposal.review","context.summarize"],"fallback_chain":["yellow-brain-efficient"],"enabled":false}'
WriteExpert "yellow-brain-primary" '{"schema":"leafos.expert.v1","id":"yellow-brain-primary","model_ref":"qwen3.6-27b-fable","source_repo":"'+$repo+'","revision":"main","parameters_b":27,"provider":"llama.cpp","placement":"local","stack_segment":"local_gpu","endpoint_ref":"local-brain","quantization":"Q6_K_MTP","estimated_memory_gib":22.0,"context_tokens":32768,"capabilities":["proposal.review","route.plan"],"fallback_chain":["yellow-brain-efficient","yellow-brain-feeder"],"enabled":false}'
WriteExpert "yellow-brain-efficient" '{"schema":"leafos.expert.v1","id":"yellow-brain-efficient","model_ref":"qwen3.6-27b-fable","source_repo":"'+$repo+'","revision":"main","parameters_b":27,"provider":"llama.cpp","placement":"local","stack_segment":"local_gpu","endpoint_ref":"local-brain","quantization":"Q5_K_M_MTP","estimated_memory_gib":18.0,"context_tokens":32768,"capabilities":["proposal.review"],"fallback_chain":["yellow-brain-feeder"],"enabled":false}'
WriteExpert "yellow-brain-bedrock" '{"schema":"leafos.expert.v1","id":"yellow-brain-bedrock","model_ref":"qwen3.6-27b-fable","source_repo":"'+$repo+'","revision":"main","parameters_b":27,"provider":"llama.cpp","placement":"local","stack_segment":"local_cpu","endpoint_ref":"local-brain","quantization":"Q8_0_MTP","estimated_memory_gib":27.0,"context_tokens":32768,"capabilities":["proposal.review","judge.local"],"fallback_chain":["yellow-brain-primary"],"enabled":false}'

# Code
WriteExpert "yellow-coder-fast" '{"schema":"leafos.expert.v1","id":"yellow-coder-fast","model_ref":"qwen3.6-27b-fable","source_repo":"'+$repo+'","revision":"main","parameters_b":27,"provider":"llama.cpp","placement":"local","stack_segment":"local_gpu","endpoint_ref":"local-coder","quantization":"Q4_K_S","estimated_memory_gib":14.0,"context_tokens":32768,"capabilities":["proposal.patch","diagnostic.compile"],"fallback_chain":["yellow-coder-primary"],"enabled":false}'
WriteExpert "yellow-coder-primary" '{"schema":"leafos.expert.v1","id":"yellow-coder-primary","model_ref":"qwen3.6-27b-fable","source_repo":"'+$repo+'","revision":"main","parameters_b":27,"provider":"llama.cpp","placement":"local","stack_segment":"local_gpu","endpoint_ref":"local-coder","quantization":"Q5_K_M","estimated_memory_gib":18.0,"context_tokens":32768,"capabilities":["proposal.patch","diagnostic.compile","diagnostic.lint"],"fallback_chain":["yellow-coder-review","yellow-coder-fast"],"enabled":false}'
WriteExpert "yellow-coder-review" '{"schema":"leafos.expert.v1","id":"yellow-coder-review","model_ref":"qwen3.6-27b-fable","source_repo":"'+$repo+'","revision":"main","parameters_b":27,"provider":"llama.cpp","placement":"local","stack_segment":"local_gpu","endpoint_ref":"local-coder","quantization":"Q6_K","estimated_memory_gib":22.0,"context_tokens":32768,"capabilities":["proposal.patch","proposal.review"],"fallback_chain":["yellow-coder-primary"],"enabled":false}'
WriteExpert "yellow-coder-bedrock" '{"schema":"leafos.expert.v1","id":"yellow-coder-bedrock","model_ref":"qwen3.6-27b-fable","source_repo":"'+$repo+'","revision":"main","parameters_b":27,"provider":"llama.cpp","placement":"local","stack_segment":"local_cpu","endpoint_ref":"local-coder","quantization":"Q8_0","estimated_memory_gib":27.0,"context_tokens":32768,"capabilities":["proposal.patch","proposal.review"],"fallback_chain":["yellow-coder-review"],"enabled":false}'

# Critic
WriteExpert "yellow-critic-fast" '{"schema":"leafos.expert.v1","id":"yellow-critic-fast","model_ref":"qwen3.6-27b-fable","source_repo":"'+$repo+'","revision":"main","parameters_b":27,"provider":"llama.cpp","placement":"local","stack_segment":"local_gpu","endpoint_ref":"local-critic","quantization":"IQ4_NL","estimated_memory_gib":9.0,"context_tokens":32768,"capabilities":["proposal.review","qa"],"fallback_chain":["yellow-critic-primary"],"enabled":false}'
WriteExpert "yellow-critic-primary" '{"schema":"leafos.expert.v1","id":"yellow-critic-primary","model_ref":"qwen3.6-27b-fable","source_repo":"'+$repo+'","revision":"main","parameters_b":27,"provider":"llama.cpp","placement":"local","stack_segment":"local_gpu","endpoint_ref":"local-critic","quantization":"Q5_K_M","estimated_memory_gib":18.0,"context_tokens":32768,"capabilities":["proposal.review","qa"],"fallback_chain":["yellow-critic-bedrock"],"enabled":false}'
WriteExpert "yellow-critic-bedrock" '{"schema":"leafos.expert.v1","id":"yellow-critic-bedrock","model_ref":"qwen3.6-27b-fable","source_repo":"'+$repo+'","revision":"main","parameters_b":27,"provider":"llama.cpp","placement":"local","stack_segment":"local_cpu","endpoint_ref":"local-critic","quantization":"Q8_0","estimated_memory_gib":27.0,"context_tokens":32768,"capabilities":["proposal.review","qa","judge.local"],"fallback_chain":["yellow-critic-primary"],"enabled":false}'

# Writer
WriteExpert "yellow-writer-fast" '{"schema":"leafos.expert.v1","id":"yellow-writer-fast","model_ref":"qwen3.6-27b-fable","source_repo":"'+$repo+'","revision":"main","parameters_b":27,"provider":"llama.cpp","placement":"local","stack_segment":"local_gpu","endpoint_ref":"local-writer","quantization":"Q4_K_M","estimated_memory_gib":14.0,"context_tokens":32768,"capabilities":["write.fast","context.summarize"],"fallback_chain":["yellow-writer-primary"],"enabled":false}'
WriteExpert "yellow-writer-primary" '{"schema":"leafos.expert.v1","id":"yellow-writer-primary","model_ref":"qwen3.6-27b-fable","source_repo":"'+$repo+'","revision":"main","parameters_b":27,"provider":"llama.cpp","placement":"local","stack_segment":"local_gpu","endpoint_ref":"local-writer","quantization":"Q5_K_M","estimated_memory_gib":18.0,"context_tokens":32768,"capabilities":["write.primary","context.summarize"],"fallback_chain":["yellow-writer-bedrock"],"enabled":false}'
WriteExpert "yellow-writer-bedrock" '{"schema":"leafos.expert.v1","id":"yellow-writer-bedrock","model_ref":"qwen3.6-27b-fable","source_repo":"'+$repo+'","revision":"main","parameters_b":27,"provider":"llama.cpp","placement":"local","stack_segment":"local_cpu","endpoint_ref":"local-writer","quantization":"Q8_0","estimated_memory_gib":27.0,"context_tokens":32768,"capabilities":["write.primary","context.summarize"],"fallback_chain":["yellow-writer-primary"],"enabled":false}'

# Judge
WriteExpert "yellow-judge-local" '{"schema":"leafos.expert.v1","id":"yellow-judge-local","model_ref":"qwen3.6-27b-fable","source_repo":"'+$repo+'","revision":"main","parameters_b":27,"provider":"llama.cpp","placement":"local","stack_segment":"local_gpu","endpoint_ref":"local-judge","quantization":"Q6_K","estimated_memory_gib":22.0,"context_tokens":32768,"capabilities":["judge.local","proposal.review"],"fallback_chain":["yellow-judge-bedrock"],"enabled":false}'
WriteExpert "yellow-judge-bedrock" '{"schema":"leafos.expert.v1","id":"yellow-judge-bedrock","model_ref":"qwen3.6-27b-fable","source_repo":"'+$repo+'","revision":"main","parameters_b":27,"provider":"llama.cpp","placement":"local","stack_segment":"local_cpu","endpoint_ref":"local-judge","quantization":"F16","estimated_memory_gib":54.0,"context_tokens":32768,"capabilities":["judge.local","judge.bedrock"],"fallback_chain":["kimi-k27-code-remote","deepseek-v3-qa-remote"],"enabled":false}'

# HelperText
WriteExpert "yellow-helpertext-primary" '{"schema":"leafos.expert.v1","id":"yellow-helpertext-primary","model_ref":"minicpm5-1b-fable","source_repo":"GnLOLot/MiniCPM5-1B-Claude-Opus-Fable5-Thinking-GGUF","revision":"main","parameters_b":1,"provider":"llama.cpp","placement":"local","stack_segment":"local_gpu","endpoint_ref":"local-helpertext","quantization":"Q8_0","estimated_memory_gib":2.0,"context_tokens":8192,"capabilities":["write.fast"],"fallback_chain":["yellow-helpertext-bedrock"],"enabled":false}'
WriteExpert "yellow-helpertext-bedrock" '{"schema":"leafos.expert.v1","id":"yellow-helpertext-bedrock","model_ref":"minicpm5-1b-fable","source_repo":"GnLOLot/MiniCPM5-1B-Claude-Opus-Fable5-Thinking-GGUF","revision":"main","parameters_b":1,"provider":"llama.cpp","placement":"local","stack_segment":"local_cpu","endpoint_ref":"local-helpertext","quantization":"F16","estimated_memory_gib":3.5,"context_tokens":8192,"capabilities":["write.fast"],"fallback_chain":["yellow-helpertext-primary"],"enabled":false}'
